### ISSUE TITLE
Oracle Java end of life

### ISSUE THREAD

**Issue by thawn** [fiji/fiji.github.io#1]
Updating my java SDK, I just got this very unfriendly note by Oracle, that they will commercialize Java starting 2019:
http://www.oracle.com/technetwork/java/eol-135779.html
This means, that all java based applications should think about switching to alternatives.
One good alternative would be [Iced Tea](https://icedtea.classpath.org/wiki/Main_Page). 
In order to make sure that Fiji runs on Iced Tea, it may be good to start testing compatibility and smooth out any issues.

**Comment by ctrueden** [comment]
@thawn That's just for Java 8, not for Java as a whole. And it is not "commercialization" but rather End-Of-Life, so that they don't have the support burden of many old versions of Java forever. We will want to migrate Fiji to Java 10 (and beyond) at some point. But Java 8 is still fine for now.

If you want to discuss this further, a good place would be the [ImageJ Forum](http://forum.imagej.net/). This repository is just for issues with the Fiji website at https://fiji.sc/
