### ISSUE TITLE
Some Images in Plugin Switchers are 404s

### ISSUE THREAD

**Issue by mattxwang** [fiji/fiji.github.io#11]
Hi @ctrueden, I hope all is well! I just wanted to let you know that some of the images are 404'd on the Fiji plugins page. I think it's because some of the images were only uploaded to temporary image hosting (e.g. from a forum post or some cached upload) - you might want to upload it to the repository or get a more permanent source.

I'm happy to help out if there's a way I can! And let me know if there's anything else web-related I can do for Fiji/SCIFIO/associated projects!

**Comment by ctrueden** [comment]
@malsf21 Thanks for the heads up. Those images were posted to forum.image.sc on [this thread](https://forum.image.sc/t/which-fiji-plugins-should-be-featured-on-the-front-page/25168). It seems that they have now migrated to different storage. Fortunately, the URL paths remain the same—only the subdomain changed. So easily fixed by d428e98fb0fac84a2750b1eab5e9e684d1c0dcf2!
